### ISSUE TITLE
Print vs Python 3.x

### ISSUE THREAD

**Issue by wrygiel** [brouberol/contexttimer#10]
Hi!

Your recent upgrade just broke my build. You have `Programming Language :: Python :: 3` among your supported Python versions, but you have included a Python2-style `print` statement.

Could you please release a new version with a fix for that ASAP? :)

**Comment by brouberol** [comment]
Done! Sorry about that, I merged the PR before my breakfast tea.. Released under 0.3.3 version

**Comment by wrygiel** [comment]
Thanks! :) I have this on a number of production sites with `contexttimer >=0.2.0, <0.3.0` in `requriements.txt`, so this should fix the issue.

BTW, you are missing some tags in your repository.
* https://pypi.python.org/simple/contexttimer/ (8 of them here)
* https://github.com/brouberol/contexttimer/releases (only 3)
