### ISSUE TITLE
Source package should include the text of the license(s) in its own file

### ISSUE THREAD

**Issue by sundeep-co-in** [brouberol/contexttimer#6]
Packaging contexttimer for fedora and would like to suggest: include license text in its own file. You may refer [LicensingGuidelines](https://fedoraproject.org/wiki/Packaging:LicensingGuidelines#License_Text)

Thanks.

**Comment by brouberol** [comment]
First off, thanks for packaging contexttimer for fedora, that's awesome!
Second, thanks for pointing this issue to me. Do you think I should include the license in the `__init__.py` file ?

**Comment by sundeep-co-in** [comment]
Just include a LICENSE file and put text: something like https://github.com/zanata/zanata-python-client/blob/master/COPYING

**Comment by brouberol** [comment]
Right. On it. Cheers.

**Comment by brouberol** [comment]
Done.

**Comment by sundeep-co-in** [comment]
:+1:

**Comment by sundeep-co-in** [comment]
https://apps.fedoraproject.org/packages/python-contexttimer

**Comment by brouberol** [comment]
LOOK MA, I'M ON THE FEDORAS.
